name: "GO Generics Workflow"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Setup go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17 

    - name: Install beta version
      run: |
        go install golang.org/dl/go1.18beta1@latest
        go1.18beta1 download
        cp $(which go1.18beta1) $(which go)
        go version

    - name: "Test"
      run: go test -v go test -v ./pkg/container/rbtree/