name: "GO Generics Workflow"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
    - name: Check out code
      uses: actions/checkout@v4.0.0

    - name: Setup go
      uses: actions/setup-go@v4.1.0
      with:
        go-version: 1.21 

    - name: "Test"
      run: go test -v ./pkg/container/rbtree/
